# Generated by Django 2.2.11 on 2020-04-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfoThreshold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_threshold', models.FloatField(default=99.0)),
                ('memory_threshold', models.FloatField(default=99.0)),
                ('disk_threshold', models.FloatField(default=99.0)),
            ],
        ),
    ]
