# Generated by Django 2.2.11 on 2020-04-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfothreshold',
            name='server_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
